services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud_password
    networks:
      - nextcloud_network

  nextcloud:
    build: .
    restart: always
    ports:
      - "8081:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud_password
      NEXTCLOUD_TRUSTED_DOMAINS: localhost 127.0.0.1
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin_password


    depends_on:
      - db
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    driver: bridge 